from enum import StrEnum


class SessionState(StrEnum):
    CONNECTED = "CONNECTED"
    LISTENING = "LISTENING"
    STOPPING = "STOPPING"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class TurnState(StrEnum):
    IDLE = "IDLE"
    SPEECH_ACTIVE = "SPEECH_ACTIVE"
    FINALIZING_ASR = "FINALIZING_ASR"
    TRANSLATING = "TRANSLATING"
    SYNTHESIZING = "SYNTHESIZING"
    STREAMING_AUDIO = "STREAMING_AUDIO"
    TURN_COMPLETED = "TURN_COMPLETED"
    FAILED = "FAILED"
